# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeSDK.Model.AddOrganizationUsersRequest do
  @moduledoc false

  @derive [Poison.Encoder]
  defstruct [
    :users
  ]

  @type t :: %__MODULE__{
          :users => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: KindeSDK.Model.AddOrganizationUsersRequest do
  def decode(value, _options) do
    value
  end
end
