# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeSDK.Model.CreateUserRequestIdentitiesInner do
  @moduledoc """
  The result of the user creation operation
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :details
  ]

  @type t :: %__MODULE__{
          :type => String.t() | nil,
          :details => KindeSDK.Model.CreateUserRequestIdentitiesInnerDetails.t() | nil
        }
end

defimpl Poison.Decoder, for: KindeSDK.Model.CreateUserRequestIdentitiesInner do
  import KindeSDK.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :details,
      :struct,
      KindeSDK.Model.CreateUserRequestIdentitiesInnerDetails,
      options
    )
  end
end
