# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeSDK.Model.CreateUser200Response do
  @moduledoc false

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :created,
    :identities
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :created => boolean() | nil,
          :identities => [KindeSDK.Model.UserIdentity.t()] | nil
        }
end

defimpl Poison.Decoder, for: KindeSDK.Model.CreateUser200Response do
  import KindeSDK.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:identities, :list, KindeSDK.Model.UserIdentity, options)
  end
end
