# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeSDK.Model.Organization do
  @moduledoc false

  @derive [Poison.Encoder]
  defstruct [
    :code,
    :name,
    :is_default
  ]

  @type t :: %__MODULE__{
          :code => String.t() | nil,
          :name => String.t() | nil,
          :is_default => boolean() | nil
        }
end

defimpl Poison.Decoder, for: KindeSDK.Model.Organization do
  def decode(value, _options) do
    value
  end
end
