# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeSDK.Model.RemoveOrganizationUsers200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :message,
    :users_added
  ]

  @type t :: %__MODULE__{
          :message => String.t() | nil,
          :users_added => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: KindeSDK.Model.RemoveOrganizationUsers200Response do
  def decode(value, _options) do
    value
  end
end
