# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeSDK.Model.UserProfile do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :preferred_email,
    :provided_id,
    :last_name,
    :first_name
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :preferred_email => String.t() | nil,
          :provided_id => String.t() | nil,
          :last_name => String.t() | nil,
          :first_name => String.t() | nil
        }
end

defimpl Poison.Decoder, for: KindeSDK.Model.UserProfile do
  def decode(value, _options) do
    value
  end
end
