# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeSDK.Api.Users do
  @moduledoc """
  API calls for all endpoints tagged `Users`.
  """

  alias KindeSDK.Connection
  import KindeSDK.RequestBuilder

  @doc """
  Assign Users to an Organization
  Add existing users to an organization.

  ### Parameters

  - `connection` (KindeSDK.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:code` (String.t): The organization's code.
    - `:body` (AddOrganizationUsersRequest):

  ### Returns

  - `{:ok, KindeSDK.Model.AddOrganizationUsers200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec add_organization_users(Tesla.Env.client(), keyword()) ::
          {:ok, nil}
          | {:ok, KindeSDK.Model.AddOrganizationUsers200Response.t()}
          | {:error, Tesla.Env.t()}
  def add_organization_users(connection, opts \\ []) do
    optional_params = %{
      :code => :query,
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/api/v1/organization/users")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %KindeSDK.Model.AddOrganizationUsers200Response{}},
      {204, false},
      {400, false},
      {403, false},
      {404, false}
    ])
  end

  @doc """
  Create User
  Creates a user record and optionally zero or more identities for the user. An example identity could be the email address of the user.

  ### Parameters

  - `connection` (KindeSDK.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (CreateUserRequest): The details of the user to create.

  ### Returns

  - `{:ok, KindeSDK.Model.CreateUser200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_user(Tesla.Env.client(), keyword()) ::
          {:ok, nil} | {:ok, KindeSDK.Model.CreateUser200Response.t()} | {:error, Tesla.Env.t()}
  def create_user(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/api/v1/user")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %KindeSDK.Model.CreateUser200Response{}},
      {403, false}
    ])
  end

  @doc """
  Delete User
  Delete a user record

  ### Parameters

  - `connection` (KindeSDK.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:id` (String.t): The user's id.

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec deleteuser(Tesla.Env.client(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def deleteuser(connection, opts \\ []) do
    optional_params = %{
      :id => :query
    }

    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/user")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {400, false},
      {403, false},
      {404, false}
    ])
  end

  @doc """
  List Organization Users
  Get users in an organizaiton.

  ### Parameters

  - `connection` (KindeSDK.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:sort` (String.t): Field and order to sort the result by.
    - `:page_size` (integer()): Number of results per page. Defaults to 10 if parameter not sent.
    - `:next_token` (String.t): A string to get the next page of results if there are more results.
    - `:code` (String.t): The organization's code.

  ### Returns

  - `{:ok, KindeSDK.Model.OrganizationUser.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_organization_users(Tesla.Env.client(), keyword()) ::
          {:ok, nil} | {:ok, KindeSDK.Model.OrganizationUser.t()} | {:error, Tesla.Env.t()}
  def get_organization_users(connection, opts \\ []) do
    optional_params = %{
      :sort => :query,
      :page_size => :query,
      :next_token => :query,
      :code => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/organization/users")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %KindeSDK.Model.OrganizationUser{}},
      {403, false}
    ])
  end

  @doc """
  Get User
  Retrieve a user record

  ### Parameters

  - `connection` (KindeSDK.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:id` (String.t): The user's id.

  ### Returns

  - `{:ok, KindeSDK.Model.User.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_user(Tesla.Env.client(), keyword()) ::
          {:ok, nil} | {:ok, KindeSDK.Model.User.t()} | {:error, Tesla.Env.t()}
  def get_user(connection, opts \\ []) do
    optional_params = %{
      :id => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/user")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %KindeSDK.Model.User{}},
      {400, false},
      {403, false},
      {404, false}
    ])
  end

  @doc """
  List Users
  The returned list can be sorted by full name or email address in ascending or descending order. The number of records to return at a time can also be controlled using the `page_size` query string parameter.

  ### Parameters

  - `connection` (KindeSDK.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:sort` (String.t): Field and order to sort the result by.
    - `:page_size` (integer()): Number of results per page. Defaults to 10 if parameter not sent.
    - `:user_id` (integer()): ID of the user to filter by.
    - `:next_token` (String.t): A string to get the next page of results if there are more results.

  ### Returns

  - `{:ok, [%User{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_users(Tesla.Env.client(), keyword()) ::
          {:ok, nil} | {:ok, list(KindeSDK.Model.User.t())} | {:error, Tesla.Env.t()}
  def get_users(connection, opts \\ []) do
    optional_params = %{
      :sort => :query,
      :page_size => :query,
      :user_id => :query,
      :next_token => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/users")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, [%KindeSDK.Model.User{}]},
      {403, false}
    ])
  end

  @doc """
  Remove Users from an Organization
  Remove existing users from an organization.

  ### Parameters

  - `connection` (KindeSDK.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:code` (String.t): The organization's code.
    - `:body` (RemoveOrganizationUsersRequest):

  ### Returns

  - `{:ok, KindeSDK.Model.RemoveOrganizationUsers200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec remove_organization_users(Tesla.Env.client(), keyword()) ::
          {:ok, nil}
          | {:ok, KindeSDK.Model.RemoveOrganizationUsers200Response.t()}
          | {:error, Tesla.Env.t()}
  def remove_organization_users(connection, opts \\ []) do
    optional_params = %{
      :code => :query,
      :body => :body
    }

    request =
      %{}
      |> method(:patch)
      |> url("/api/v1/organization/users")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %KindeSDK.Model.RemoveOrganizationUsers200Response{}},
      {204, false},
      {400, false},
      {403, false},
      {404, false}
    ])
  end

  @doc """
  Update User
  Update a user record

  ### Parameters

  - `connection` (KindeSDK.Connection): Connection to server
  - `update_user_request` (UpdateUserRequest): The user to update.
  - `opts` (keyword): Optional parameters
    - `:id` (String.t): The user's id.

  ### Returns

  - `{:ok, KindeSDK.Model.User.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_user(Tesla.Env.client(), KindeSDK.Model.UpdateUserRequest.t(), keyword()) ::
          {:ok, nil} | {:ok, KindeSDK.Model.User.t()} | {:error, Tesla.Env.t()}
  def update_user(connection, update_user_request, opts \\ []) do
    optional_params = %{
      :id => :query
    }

    request =
      %{}
      |> method(:patch)
      |> url("/api/v1/user")
      |> add_param(:body, :body, update_user_request)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %KindeSDK.Model.User{}},
      {400, false},
      {403, false},
      {404, false}
    ])
  end
end
