# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeManagementAPI.Model.AddOrganizationUsersRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :users
  ]

  @type t :: %__MODULE__{
    :users => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: KindeManagementAPI.Model.AddOrganizationUsersRequest do
  def decode(value, _options) do
    value
  end
end

