# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeManagementAPI.Model.AddOrganizationUsers200Response do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :message,
    :users_add
  ]

  @type t :: %__MODULE__{
    :message => String.t | nil,
    :users_add => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: KindeManagementAPI.Model.AddOrganizationUsers200Response do
  def decode(value, _options) do
    value
  end
end

