# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeManagementAPI.Model.CreateUserRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :profile,
    :identities
  ]

  @type t :: %__MODULE__{
    :profile => KindeManagementAPI.Model.CreateUserRequestProfile.t | nil,
    :identities => [KindeManagementAPI.Model.CreateUserRequestIdentitiesInner.t] | nil
  }
end

defimpl Poison.Decoder, for: KindeManagementAPI.Model.CreateUserRequest do
  import KindeManagementAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:profile, :struct, KindeManagementAPI.Model.CreateUserRequestProfile, options)
    |> deserialize(:identities, :list, KindeManagementAPI.Model.CreateUserRequestIdentitiesInner, options)
  end
end

