# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeManagementAPI.Model.CreateUser200Response do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :created,
    :identities
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :created => boolean() | nil,
    :identities => [KindeManagementAPI.Model.UserIdentity.t] | nil
  }
end

defimpl Poison.Decoder, for: KindeManagementAPI.Model.CreateUser200Response do
  import KindeManagementAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:identities, :list, KindeManagementAPI.Model.UserIdentity, options)
  end
end

