# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeManagementAPI.Model.OrganizationUser do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :user_id,
    :email,
    :full_name,
    :last_name,
    :first_name
  ]

  @type t :: %__MODULE__{
    :user_id => integer() | nil,
    :email => String.t | nil,
    :full_name => String.t | nil,
    :last_name => String.t | nil,
    :first_name => String.t | nil
  }
end

defimpl Poison.Decoder, for: KindeManagementAPI.Model.OrganizationUser do
  def decode(value, _options) do
    value
  end
end

