# NOTE: This file is auto generated by OpenAPI Generator 6.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KindeManagementAPI.Model.UserIdentity do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :result
  ]

  @type t :: %__MODULE__{
    :type => String.t | nil,
    :result => KindeManagementAPI.Model.UserIdentityResult.t | nil
  }
end

defimpl Poison.Decoder, for: KindeManagementAPI.Model.UserIdentity do
  import KindeManagementAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:result, :struct, KindeManagementAPI.Model.UserIdentityResult, options)
  end
end

